name: Build and Deploy to Minikube

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: py-app
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker

    - name: Start Minikube
      run: minikube start --wait=all

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy to Minikube using Helm
      run: |
        helm upgrade --install Helm ./helm \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME \
          --set image.tag=$IMAGE_TAG
